version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'daily'
      time: '06:00'
      timezone: 'Europe/Berlin'
    assignees:
      - 'aessing'
    commit-message:
      prefix: 'Github Actions'
      include: 'scope'
    labels:
      - 'dependencies'
    open-pull-requests-limit: 10
    pull-request-branch-name:
      separator: '-'
    reviewers:
      - 'aessing'
