- name: status - needs triage
  description: New issues/PRs that need review
  color: 27ae60 # green
- name: status - in progress
  description: Actively being worked on
  color: 2ecc40 # green
- name: status - blocked
  description: Blocked by something else
  color: 16a085 # green
- name: status - ready for review
  description: Ready for code review
  color: 1abc9c # green
- name: type - enhancement
  description: Improvements to existing features
  color: 2986cc # blue
- name: type - refactor
  description: Code refactoring, no user-facing change
  color: 1d76db # blue
- name: type - test
  description: Related to tests or test coverage
  color: 0052cc # blue
- name: type - ci
  description: Continuous integration/config changes
  color: 0074d9 # blue
- name: type - chore
  description: Maintenance, build, or non-feature work
  color: 3399ff # blue
- name: type - breaking change
  description: Changes that will break something in the next release
  color: ff69b4 # pink
- name: type - bug
  description: Something isn't working as expected
  color: d80000 # red
- name: type - documentation
  description: Improvements or additions to documentation
  color: 5dade2 # blue
- name: priority - low
  description: Lowest priority
  color: ffc300 # orange
- name: priority - medium
  description: Medium priority
  color: ff9900 # orange
- name: priority - high
  description: Highest priority
  color: ff5733 # orange
- name: good first issue
  description: Good for newcomers
  color: a259ff # purple
- name: wontfix
  description: This will not be worked on
  color: ffffff
