---
apiVersion: v1
kind: Namespace
metadata:
  name: chrony
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: chrony-config
  namespace: chrony
data:
  chrony.conf: |-
  # =============================================================================
  # Chrony Configuration File
  # Chrony Time Server Container
  # https://github.com/aessing/chronyd-container
  # -----------------------------------------------------------------------------
  # Developer.......: Andre Essing (https://github.com/aessing)
  #                                (https://www.linkedin.com/in/aessing/)
  # -----------------------------------------------------------------------------
  # THIS CODE AND INFORMATION ARE PROVIDED "AS IS" WITHOUT WARRANTY OF ANY KIND,
  # EITHER EXPRESSED OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE IMPLIED
  # WARRANTIES OF MERCHANTABILITY AND/OR FITNESS FOR A PARTICULAR PURPOSE.
  # =============================================================================

  # Which servers should Chrony use to get the time from?
  pool 0.de.pool.ntp.org iburst maxsources 3
  pool 1.de.pool.ntp.org iburst maxsources 3
  pool 2.de.pool.ntp.org iburst maxsources 3
  pool 3.de.pool.ntp.org iburst maxsources 3

  # Some files and directories to store information
  driftfile /var/lib/chrony/chrony.drift
  dumpdir /run/chrony

  # When and how should Chrony correct the time offset
  makestep 0.1 3

  # Allow NTP client access from all RFC-1918 addresses
  allow 127.0.0.1
  allow 10.0.0.0/8
  allow 172.16.0.0/12
  allow 192.168.0.0/16

  # Disables command port. Chrony will not listen on port 323
  cmdport 0
---
apiVersion: v1
kind: Service
metadata:
  name: chrony
  namespace: chrony
  labels:
    app: chrony
spec:
  selector:
    app: chrony
  ports:
    - protocol: UDP
      port: 123
      targetPort: 123
      name: time
---
apiVersion: traefik.io/v1alpha1
kind: IngressRouteUDP
metadata:
  name: chrony-udp
  namespace: chrony
  annotations:
    kubernetes.io/ingress.class: traefik-external
spec:
  entryPoints:
    - time
  routes:
    - services:
        - name: chrony
          port: 123
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chrony
  namespace: chrony
spec:
  selector:
    matchLabels:
      app: chrony
  replicas: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: chrony
    spec:
      restartPolicy: Always
      containers:
        - name: chrony
          image: aessing/chronyd:1.0.0
          resources:
            requests:
              memory: 16Mi
              cpu: 0.5
            limits:
              memory: 64Mi
              cpu: 1
          ports:
            - containerPort: 123
              protocol: UDP
              name: time
          volumeMounts:
            - name: chrony-config
              mountPath: /etc/chrony/chrony.conf
              subPath: chrony.conf
              readOnly: true
      volumes:
        - name: chrony-config
          configMap:
            name: chrony-config
