name: Label Syncer
on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - .github/label-syncer/label-syncer.yml

jobs:
  build:
    name: Sync repository labels from file
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        id: checkout-code
        uses: actions/checkout@v3
      - name: Sync repository labels from file
        id: labeling
        uses: micnncim/action-label-syncer@v1
        if: success()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          manifest: .github/label-syncer/label-syncer.yml
